name: ci-golang

on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: Run Test
        run: go test --coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Variaveis de Ambiente"  
          echo "GITHUB_TOKEN = $GITHUB_TOKEN"
          echo "SONAR_TOKEN = $SONAR_TOKEN"

      - name: Run Application
        run: go run calculo.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fabiohf/test-ci:latest